
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sparse-checkout-list-dir
spec:
  description: |
    sparse-checkout-list-dir takes a git repository and a list of
    directory patterns to match and lists all cloned files and directories.
    This is an example pipeline demonstrating the following:
      - Using the git-clone catalog Task to clone a specific set of
        files based on directory patterns.
      - Passing a cloned repo to subsequent Tasks using a Workspace.
      - Ordering Tasks in a Pipeline using "runAfter" so that
        git-clone completes before we try to read from the Workspace.
      - Using a volumeClaimTemplate Volume as a Workspace.
      - Avoiding hard-coded paths by using a Workspace's path
        variable instead.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: dockerImageUrl
    type: string
    description: Docker Image URL to push the image
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task to list all cloned files and directories.
  - name: dockerconfig-secret
    description: |
      This workspace will have docker config.json
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-maven
    runAfter: ["fetch-repo"]
    taskRef:
      name: build-maven
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: workingDir
      value: $(workspaces.source.path)
  - name: build-kaniko
    runAfter: ["build-maven"]
    taskRef:
      name: build-kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: dockerconfig-secret
    params:
    - name: IMAGE
      value: $(params.dockerImageUrl)
    - name: DOCKERFILE
      value: $(workspaces.source.path)/Dockerfile
    - name: CONTEXT
      value: ./
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-sparse-checkout
spec:
  pipelineRef:
    name: sparse-checkout-list-dir
  workspaces:
  - name: dockerconfig-secret
    configmap:
      name: my-config
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/dcanadillas/petclinic-kaniko.git
  - name: dockerImageUrl
    value: synectiks/docker-builders:kaniko