apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
data:
  config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVHWnZjbTFoZEdsdmJqcFRlVzR6WTNRaGF5UlFkSEpBTWpBeE1HRmlZMlE9IgoJCX0KCX0KfQ==
