apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-both
  namespace: tekton-pipelines
spec:
  params:
    - name: directory1
      type: string
    - name: directory2
      type: string
  workspaces:
    - name: local-ws
  steps:
    - name: read-1
      image: ubuntu
      script: cat $(workspaces.local-ws.path)/$(params.directory1)/foo | grep bar
    - name: read-2
      image: ubuntu
      script: cat $(workspaces.local-ws.path)/$(params.directory2)/foo | grep bar
