apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |-
    [devops-cicd]
    aws_access_key_id     = AKIAZSLS3RLM3AKJGSP7
    aws_secret_access_key = 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

    [default]
    aws_access_key_id     = AKIAZSLS3RLM3AKJGSP7
    aws_secret_access_key = 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
  config: |-
    [profile devops-cicd]
    region = us-east-1
    output = text
    [default]
    region = us-east-1
