apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |-
    [devops-cicd]
    aws_access_key_id     = <aws_access_key_id>
    aws_secret_access_key = <aws_secret_access_key>

    [default]
    aws_access_key_id     = <aws_access_key_id>
    aws_secret_access_key = <aws_secret_access_key>
  config: |-
    [profile devops-cicd]
    region = us-east-1
    output = text
    [default]
    region = us-east-1
